services:
  - type: web
    name: taskmanager-backend
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: DATABASE_URL
        value: "your-database-url"
    autoDeploy: true
  - type: web
    name: taskmanager-frontend
    env: node
    buildCommand: "npm install"
    startCommand: "npm run build"
    envVars:
      - key: REACT_APP_API_URL
        value: "your-api-url"
    autoDeploy: true
